### PR TITLE
Fix issue with php7

### PR DESCRIPTION
**Pull request by belgattitude**
Just aliased the dev/deature/php7 as 2.0. Not very clean, to be changed when 2.0 is out

```
"fabfuel/prophiler": "^1.4|dev-feature/php7 as 2.0",
```

### CODE REVIEW

**Comment by belgattitude** [comment]
Linked to https://github.com/zendframework/zend-expressive-skeleton/issues/157

**Comment by belgattitude** [comment]
Linked to https://github.com/bitExpert/prophiler-psr7-middleware/issues/17

**Comment by belgattitude** [comment]
At this time it works, but travis complains about security checker...

On my machine it works perfect. So I guess a travis problem ?

```
BUILD FAILED

/home/travis/build/bitExpert/prophiler-psr7-middleware/vendor/bitexpert/phing-securitychecker/build.xml:7:34: 

#0 /home/travis/build/bitExpert/prophiler-psr7-middleware/vendor/phing/phing/classes/phing/UnknownElement.php(100): bitExpert\Phing\SecurityChecker\SecurityCheckerTask->main()

#1 /home/travis/build/bitExpert/prophiler-psr7-middleware/vendor/phing/phing/classes/phing/Task.php(283): UnknownElement->main()

#2 /home/travis/build/bitExpert/prophiler-psr7-middleware/vendor/phing/phing/classes/phing/Target.php(336): Task->perform()

#3 /home/travis/build/bitExpert/prophiler-psr7-middleware/vendor/phing/phing/classes/phing/Target.php(366): Target->main()

#4 /home/travis/build/bitExpert/prophiler-psr7-middleware/vendor/phing/phing/classes/phing/Project.php(898): Target->performTasks()

#5 /home/travis/build/bitExpert/prophiler-psr7-middleware/vendor/phing/phing/classes/phing/Project.php(868): Project->executeTarget('security:check')

#6 /home/travis/build/bitExpert/prophiler-psr7-middleware/vendor/phing/phing/classes/phing/Phing.php(723): Project->executeTargets(Array)

#7 /home/travis/build/bitExpert/prophiler-psr7-middleware/vendor/phing/phing/classes/phing/Phing.php(200): Phing->runBuild()

#8 /home/travis/build/bitExpert/prophiler-psr7-middleware/vendor/phing/phing/classes/phing/Phing.php(347): Phing::start(Array, NULL)

#9 /home/travis/build/bitExpert/prophiler-psr7-middleware/vendor/phing/phing/bin/phing.php(58): Phing::fire(Array)

#10 /home/travis/build/bitExpert/prophiler-psr7-middleware/vendor/phing/phing/bin/phing(14): require_once('/home/travis/bu...')

#11 {main}

Previous SensioLabs\Security\Exception\RuntimeException: An error occurred: gnutls_handshake() failed: A TLS fatal alert has been received.. in /home/travis/build/bitExpert/prophiler-psr7-middleware/vendor/sensiolabs/security-checker/SensioLabs/Security/Crawler/CurlCrawler.php:59

Stack trace:

#0 /home/travis/build/bitExpert/prophiler-psr7-middleware/vendor/sensiolabs/security-checker/SensioLabs/Security/Crawler/BaseCrawler.php(48): SensioLabs\Security\Crawler\CurlCrawler->doCheck('/home/travis/bu...', '/home/travis/bu...')

#1 /home/travis/build/bitExpert/prophiler-psr7-middleware/vendor/sensiolabs/security-checker/SensioLabs/Security/Crawler/DefaultCrawler.php(31): SensioLabs\Security\Crawler\BaseCrawler->check('/home/travis/bu...')
///....
```

**Comment by belgattitude** [comment]
Link to  https://github.com/sensiolabs/security-checker/pull/77

**Comment by belgattitude** [comment]
Little summary:

1. Works now with php7 and php 5.6 (solved composer requirements)
2. Removed composer.lock and added in .gitignore (vendor also added in .gitignore)
3. Modified .travis.yml to pass security-check (not 100% sure, but it works till now)

**Comment by shochdoerfer** [comment]
Thanks for your help. So was the alias enough to get it running? Feels a bit wired to me, but anyways ;)

I'd love to see 2 changes though:
 - Please add the composer.lock file again. We are part of the "always commit the lock file" team.
 - revert the changes in the .travis.yml file. I am fine if the build is broken due to problems with Travis. If we wan't to change that, that should be a separate PR to be able to better track what is going on.

**Comment by belgattitude** [comment]
In the latest update, I've reverted the travis change for security check. So for now the build fails.

**Comment by belgattitude** [comment]
But concerning:

> Please add the composer.lock file again. We are part of the "always commit the lock file" team.

I would not make that, because if we do the, `composer.lock` file will set requirements depending on which PHP version was used. In this case it would not work...

**UPDATED**

The comment below reveals wrong:

> BTW, the `composer.lock` is good to have for a project, less for a library.... But if I re-add it, the P/R does > not make sense anymore and could be closed. 
> So you'll have to make a new major version for PHP7. No problem for me

It works ;)

**Comment by belgattitude** [comment]
Re-added composer.lock :) Looks it works.

Thanks for your time.

**Comment by shochdoerfer** [comment]
Merged in master.

**Comment by belgattitude** [comment]
Great, thanks a lot.

**Pull request closed without merging**
