### PR TITLE
Fixes #8 when no Content-Type is set in the response

### LINKED ISSUE #8: If no Content-Type is set
In the response if content-type is not set the tool bar is not shown.

### PR DESCRIPTION
**Pull request by harikt**
Not a regex expert . If there is better patch please consider it .

Thank you.

### CODE REVIEW

**Comment by shochdoerfer** [comment]
According to the PSR-7 specification the [MessageInterface::getHeaderLine()](https://github.com/php-fig/http-message/blob/master/src/MessageInterface.php#L115) will always return an string so this change should not be needed. What was the problem you tried to solve?

**Comment by shochdoerfer** [comment]
There exists a hasHeader() method which might come in handy, depending on what you want to achieve ;)

**Comment by harikt** [comment]
> There exists a hasHeader() method which might come in handy, depending on what you want to achieve

yes, probably that also works.

**Comment by shochdoerfer** [comment]
See #8 for the reasons of not accepting this PR.

**Pull request closed without merging**
